### ISSUE TITLE
Installation path may be elsewhere

### ISSUE THREAD

**Issue by bgamari** [nareshv/kde-konsole-colorschemes#1]
I just stumbled around for quite a while looking for the right installation path for these `konsole` colorschemes under Debian `testing`.

On my machine they are looked for in `~/.local/share/konsole`.

**Comment by nareshv** [comment]
With latest kde, i think the paths are moved to ~/.local . I'll update the main doc to reflect the newer path as well.

```
c|..⚡ ⇒ cat /etc/issue
Ubuntu 14.04.2 LTS \n \l

c|..⚡ ⇒ ls -l ~/.local/share/konsole
ls: cannot access /home/nareshv/.local/share/konsole: No such file or directory

```

**Comment by nareshv** [comment]
updated README

Thanks for the notification.
